/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_SERVICE_H_RPCGEN
#define _RPC_SERVICE_H_RPCGEN

#include <rpc/rpc.h>

#define RPC_PROG 0x31234567
#define INIT_VERS 1
#define DATE 1
extern char **date_1();
#define CPU 2
extern float *cpu_1();
#define MEMORY 3
extern float *memory_1();
#define PROCESSES 4
extern char **processes_1();
extern int rpc_prog_1_freeresult();

#endif /* !_RPC_SERVICE_H_RPCGEN */
