#include <stdio.h>
#include <string.h>
#include <time.h>
#include <sys/types.h>
#include <rpc/rpc.h>     /* standard RPC include file */
#include "rpc_service.h" /* this file is generated by rpcgen */

#define MAX_LEN 100
long get_response(void);

long get_top_level_response()
{
    long choice;

    printf("===========================================\n");
    printf("                   Menu: \n");
    printf("-------------------------------------------\n");
    printf("                1. Time\n");
    printf("                2. CPU Usage\n");
    printf("                3. Memory Usage\n");
    printf("                4. Average Processes\n");
    printf("                5. Quit\n");
    printf("-------------------------------------------\n");
    printf("               Choice (1-5):");
    scanf("%ld", &choice);
    printf("===========================================\n");
    return (choice);
}

long get_time_response()
{
    long choice;

    printf("===========================================\n");
    printf("                   Time Menu: \n");
    printf("-------------------------------------------\n");
    printf("                1. Date\n");
    printf("                2. Time\n");
    printf("                3. Date & Time\n");
    printf("                4. Uptime\n");
    printf("-------------------------------------------\n");
    printf("               Choice (1-4):");
    scanf("%ld", &choice);
    printf("===========================================\n");
    return (choice);
}

long get_cpu_response()
{
    long choice;

    printf("===========================================\n");
    printf("                   CPU Loading Menu: \n");
    printf("-------------------------------------------\n");
    printf("                1. Current\n");
    printf("                2. Last Minute\n");
    printf("                3. Last Hour\n");
    printf("                4. Last Day\n");
    printf("-------------------------------------------\n");
    printf("               Choice (1-4):");
    scanf("%ld", &choice);
    printf("===========================================\n");
    return (choice);
}

long get_memory_response()
{
    long choice;

    printf("===========================================\n");
    printf("                   Memory Loading Menu: \n");
    printf("-------------------------------------------\n");
    printf("                1. Current\n");
    printf("                2. Last Minute\n");
    printf("                3. Last Hour\n");
    printf("                4. Last Day\n");
    printf("-------------------------------------------\n");
    printf("               Choice (1-4):");
    scanf("%ld", &choice);
    printf("===========================================\n");
    return (choice);
}

long get_processes_response()
{
    long choice;

    printf("===========================================\n");
    printf("                   Active Processes Menu: \n");
    printf("-------------------------------------------\n");
    printf("                1. Current\n");
    printf("                2. Last Minute\n");
    printf("                3. Last Hour\n");
    printf("                4. Last Day\n");
    printf("-------------------------------------------\n");
    printf("               Choice (1-4):");
    scanf("%ld", &choice);
    printf("===========================================\n");
    return (choice);
}

int main(int argc, char **argv)
{
    CLIENT *cl; /* RPC handle */
    char *server;
    char **sresult; /* return string value from RPC call*/
    float *fresult; /* return float value from RPC call*/
    static char err[] = "Invalid Response\n\0";
    char s[MAX_LEN]; /* character array to hold output */
    long response;   /* user response */
    long *lresult;   /* pointer to user response */

    if (argc != 2)
    {
        fprintf(stderr, "usage: %s hostname\n", argv[0]);
        exit(1);
    }
    server = argv[1];
    lresult = (&response);
    /*
     * Create the client "handle."
     */
    if ((cl = clnt_create(server, RPC_PROG, INIT_VERS, "udp")) == NULL)
    {
        clnt_pcreateerror(server);
        exit(2);
    }
    response = get_top_level_response();
    while (response != 5)
    {
        switch (response)
        {
        case 1:
            response = get_time_response();
            if ((sresult = date_1(lresult, cl)) == NULL)
            {
                clnt_perror(cl, server);
                exit(3);
            }
            printf("  %s\n", *sresult);
            break;
        case 2:
            response = get_cpu_response();
            if ((fresult = cpu_1(lresult, cl)) == NULL)
            {
                clnt_perror(cl, server);
                exit(3);
            }
            printf("%.3f%% Loaded\n", *fresult);
            break;
        case 3:
            response = get_memory_response();
            if ((fresult = memory_1(lresult, cl)) == NULL)
            {
                clnt_perror(cl, server);
                exit(3);
            }
            printf("%.0f\tKB used\n", *fresult);
            printf("%.0f\tMB used\n", *fresult / 1000);
            printf("%.3f\tGB used\n", *fresult / 1000000);
            break;
        case 4:
            response = get_processes_response();
            if ((sresult = date_1(lresult, cl)) == NULL)
            {
                clnt_perror(cl, server);
                exit(3);
            }
            printf("  %s\n", *sresult);
            break;
        default:
            printf(err);
            break;
        }
        response = get_top_level_response();
    }
    clnt_destroy(cl); /* done with the handle */
    exit(0);
}